dlb: Add new device plugin
bart0sh/intel-device-plugins-for-kubernetes pull request #6
Opened 2021-11-01 12:53 UTC by hj-johannes-lee

ci.yaml image added (and let me remove from the pr for libdlb-demo)
linter check problem solved

Signed-off-by: Hyeongju Johannes Lee <hyeongju.lee@intel.com>

2021-11-01 13:22 UTC, mythi reviewed
LGTM

2021-11-01 13:26 UTC, bart0sh commented
@hj-johannes-lee Please change name and description of this PR (and commit) to reflect the reality. Remember, it's going to be merged into the main PR branch. We don't want 2 commits with the same name there.

2021-11-01 13:27 UTC, bart0sh requested changes
^^^^

2021-11-01 14:01 UTC, mythi commented
> We don't want 2 commits with the same name there.

@bart0sh you don't plan to squash this into the original commit (in #4)?

2021-11-01 16:00 UTC, hj-johannes-lee commented
Yeah, I was thinking that you would just squash this into the original,, so I just copied.! If not, tell me!

2021-11-01 16:26 UTC, bart0sh commented
I don't want to squash anything that looks logical. But even if I want to do that I'd anyway prefer commits named and described adequately. For example, this PR (and commit) is called "dlb: Add new device plugin", but doesn't add any new device plugin.

2021-11-01 17:06 UTC, mythi commented
That I agree with. f09a72f0ee7bac81c5b1dc863ff02a2af2232ac0 commit message should be rewritten

2021-11-02 08:31 UTC, hj-johannes-lee commented
I see.! Let me rewrite the message.1

2021-11-02 09:47 UTC, bart0sh requested changes

2021-11-02 09:47 UTC, bart0sh commented on .github/workflows/ci.yaml
> +          - dlb-libdlb-demo
Please, remove trailing spaces.

2021-11-02 10:02 UTC, hj-johannes-lee commented on .github/workflows/ci.yaml
> +          - dlb-libdlb-demo
I immediately noticed after pushing it. Idk.. I think my visual code in linux laptop sometimes malfunctions..
I saw +2/-1 but the git log showed only one line I added for intel-dlb-plugin..! And,, after I pushed it suddenly showed that.. I don't understand.. but I changed (hoping that you would not see before I push it.. but you already saw it.!)

2021-11-02 10:03 UTC, bart0sh approved these changes
/lgtm

2021-11-02 10:03 UTC, merged